### ISSUE TITLE
Specifying a different RKHS for each continuous variable

### ISSUE THREAD

**Issue by haziqj** [haziqjamil/iprior#13]
This needs a bit more thought on how the user inputs the different RKHSs into the `iprior` function. Things can get messy when there are a lot of variables involved.

Note: By default, the centred Canonical kernel is used for continuous variables, and Pearson for categorical. But sometimes, we would like to mix Canonical with FBM, say.

**Comment by haziqj** [comment]
Perhaps this requires a new function. Say `merge()`. Putting too much features into one function such as `update()` is probably not a good idea.

Anyway, the intended function of `merge()` would be if we had fitted two types of RKHS, such as:

``` r
mod1 <- iprior(formula=y~x1, data, kernel="Canonical")
mod2 <- iprior(formula=y~x2, data, kernel="FBM")
```

Then essentially to get the model `y~x1 + x2` where `x1` uses a Canonical kernel and `x2` uses a FBM kernel, then do `merge(mod1, mod2)`.

Still debating whether to implement this, or stick to something more traditional like

``` r
mod <- iprior(y~x1+x2, data, kernel=c("Canonical", "FBM"))
```

**Comment by Wicher2** [comment]
The traditional method seems the easiest to use to me...

**Comment by haziqj** [comment]
Latest release has this feature. Will write about it in the wiki soon.
