### ISSUE TITLE
The summary function is slow for large datasets

### ISSUE THREAD

**Issue by haziqj** [haziqjamil/iprior#22]
This is probably down to the calculation of the Hessian matrix (to calculate observed Fisher information) and also inverting it. Maybe look at other methods.

**Comment by Wicher2** [comment]
Can the Hessian be passed on to the summary function from iprior.mod? Then it should be direct.

**Comment by haziqj** [comment]
No, because the exponential family EM does not maximise anything, but rather it is a sequential update of parameters. So no Hessian was produced/calculated. Yet another downside of the exponential family EM, and reason to implement the regular EM.

**Comment by Wicher2** [comment]
Ah ok, I thought maybe the Hessian can easily be derived from things computed even in exp family EM. In any case should be interesting to describe both methods in your thesis.
